# Generated by Django 4.2 on 2025-02-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_calendar_event_id_googlecalendartoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (30, "1 месяц"),
                    (90, "3 месяца"),
                    (180, "6 месяцев"),
                    (365, "1 год"),
                ],
                default=30,
            ),
        ),
    ]
