# Generated by Django 4.2 on 2025-02-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleCalendarToken",
        ),
    ]
