# Generated by Django 4.2 on 2025-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0006_subscription_shared_with_userprofile_recovery_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="folder",
        ),
        migrations.AddField(
            model_name="subscription",
            name="share_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
